# Nama workflow yang akan muncul di tab Actions GitHub
name: Deploy Laravel to Azure VM

# Pemicu: Jalankan workflow ini setiap kali ada push ke branch 'main'
on:
  push:
    branches:
      - main

# Daftar pekerjaan yang akan dijalankan
jobs:
  deploy:
    # Jenis runner yang akan digunakan
    runs-on: ubuntu-latest
    
    # Serangkaian langkah yang akan dieksekusi
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          
          echo "=> Memulai proses deployment..."
          cd /var/www/html/toko-sparepart
          
          echo "=> 1. Menarik kode terbaru dari GitHub..."
          git pull origin main
          
          # Gunakan sudo untuk semua perintah yang mengubah file
          echo "=> 2. Menginstal dependensi Composer..."
          sudo composer install --optimize-autoloader --no-dev
          
          echo "=> 3. Menyiapkan Node.js dan menginstal dependensi NPM..."
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          sudo npm install
          
          echo "=> 4. Membangun aset frontend..."
          sudo npm run build
          
          echo "=> 5. Menjalankan migrasi database..."
          sudo php artisan migrate --force
          
          echo "=> 6. Membersihkan cache aplikasi..."
          sudo php artisan optimize:clear
          
          # LANGKAH KRUSIAL: Kembalikan kepemilikan ke www-data setelah selesai
          echo "=> 7. Mengatur ulang izin folder untuk web server..."
          sudo chown -R www-data:www-data /var/www/html/toko-sparepart

          echo "✅ Deployment selesai!"

        EOF