name: Deploy Laravel to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          
          echo "=> Memulai proses deployment..."
          cd /var/www/html/toko-sparepart
          
          # LANGKAH KUNCI 1: Ambil alih kepemilikan untuk user deployment (adhim)
          echo "=> 1. Mengatur izin untuk deployment..."
          sudo chown -R adhim:adhim .
          
          # LANGKAH KUNCI 2: Sekarang git pull akan berhasil karena 'adhim' adalah pemiliknya
          echo "=> 2. Menarik kode terbaru dari GitHub..."
          git pull origin main
          
          # Sekarang jalankan sisa perintah TANPA sudo, karena 'adhim' adalah pemilik
          echo "=> 3. Menginstal dependensi Composer..."
          composer install --optimize-autoloader --no-dev
          
          echo "=> 4. Menyiapkan Node.js dan membangun aset..."
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          npm install
          npm run build
          
          echo "=> 5. Menjalankan migrasi & membersihkan cache..."
          php artisan migrate --force
          php artisan optimize:clear
          
          # LANGKAH KUNCI 3: Kembalikan kepemilikan ke www-data agar web server bisa bekerja
          echo "=> 6. Mengembalikan izin untuk web server..."
          sudo chown -R www-data:www-data .

          echo "✅ Deployment berhasil sepenuhnya!"

        EOF